// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Only configured for Web and Android.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Web and Android.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNF4LWdFrp6yLK4x_RyCnhlyQtVHxI-o',
    appId: '1:844567568423:web:147faf71de7d209a6cee02',
    messagingSenderId: '844567568423',
    projectId: 'taskflow-app-e1463',
    authDomain: 'taskflow-app-e1463.firebaseapp.com',
    storageBucket: 'taskflow-app-e1463.firebasestorage.app',
    measurementId: 'G-12441CQHH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD5uCTNk4drTEAH-ugTeLDe9v_PhzvHqA',
    appId: '1:844567568423:android:6a75fcba38857d926cee02',
    messagingSenderId: '844567568423',
    projectId: 'taskflow-app-e1463',
    storageBucket: 'taskflow-app-e1463.firebasestorage.app',
  );
}