import 'package:flutter/material.dart';
<<<<<<< HEAD
import 'screens/login.dart';

void main() {
  runApp(const TaskFlowApp());
}

class TaskFlowApp extends StatelessWidget {
  const TaskFlowApp({super.key});
=======
import 'package:firebase_core/firebase_core.dart';
import 'package:taskflow_app/firebase_options.dart'; // generated by flutterfire configure

import 'login_page.dart';
import 'register_page.dart';
import 'task_app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // must match your web project
  );
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});
>>>>>>> 1952e08e10082e5f5854338fd135925bc577fa6d

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TaskFlow',
<<<<<<< HEAD
      debugShowCheckedModeBanner: false,
      
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF00897B), 
          brightness: Brightness.light,
        ),
        
        scaffoldBackgroundColor: const Color(0xFFF7F9FC),

        appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        foregroundColor: Colors.black87,
        elevation: 1,
        surfaceTintColor: Colors.transparent,
        titleTextStyle: TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
      ),
  
        cardTheme: CardThemeData(
          color: Colors.white,
          elevation: 1,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
        ),

        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(
            foregroundColor: const Color(0xFF00897B),
          ),
        ),
      ),
      home: const LoginScreen(),
=======
      theme: ThemeData(primarySwatch: Colors.teal),
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(),
        '/tasks': (context) => const TaskPage(),
      },
>>>>>>> 1952e08e10082e5f5854338fd135925bc577fa6d
    );
  }
}