import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:taskflow_app/firebase_options.dart'; // generated by flutterfire configure

import 'login_page.dart';
import 'register_page.dart';
import 'task_app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // must match your web project
  );
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TaskFlow',
      theme: ThemeData(primarySwatch: Colors.teal),
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(),
        '/tasks': (context) => const TaskPage(),
      },
    );
  }
}